"""Top-level package for vecalex."""

from pyalex import (
    OpenAlexResponseList,
    Publisher,
    Publishers,
    autocomplete,
    invert_abstract,
)

from vecalex.vecalex import (
    Author,
    Authors,
    Concept,
    Concepts,
    Domain,
    Domains,
    Field,
    Fields,
    Funder,
    Funders,
    Institution,
    Institutions,
    Journals,
    People,
    Source,
    Sources,
    Subfield,
    Subfields,
    Topic,
    Topics,
    Work,
    Works,
    config,
)

__all__ = [
    "Author",
    "Authors",
    "Concept",
    "Concepts",
    "Domain",
    "Domains",
    "Field",
    "Fields",
    "Funder",
    "Funders",
    "Institution",
    "Institutions",
    "Journals",
    "OpenAlexResponseList",
    "People",
    "Publisher",
    "Publishers",
    "Source",
    "Sources",
    "Subfield",
    "Subfields",
    "Topic",
    "Topics",
    "Work",
    "Works",
    "autocomplete",
    "config",
    "invert_abstract",
]
